config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  devise_for :users,
    :controllers => { :registrations => 'registrations',
                      :ichain_registrations => "ichain_registrations"},
    :failure_app => Devise::IchainFailureApp

  concern :state_machine do
    resources :state_transitions, :only => [:new, :create]
    resources :state_adjustments, :only => [:new, :create]
  end

  concern :commentable do
    resources :comments, :only => [:new, :create]
  end

  resources :events do
    resources :event_emails, except: [:edit, :update, :destroy] do
      post :preview, on: :collection
    end
    get :participants, on: :member
    resources :event_organizers, except: [:edit, :update, :show] do
      get :autocomplete_user, :on => :collection
    end
  end
  resources :budgets

  resources :travel_sponsorships,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'travel_sponsorship'} do
    resource :expenses_approval, :only => [:edit, :update]
  end

  resources :shipments,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'shipment'}

  resources :requests, :only => [:index, :show] do
    resource :reimbursement, :concerns => [:state_machine, :commentable], :defaults => {:machine => 'reimbursement'} do
      resources :attachments, :only => [:show], :controller => :reimbursement_attachments
      resource  :acceptance, :only => [:new, :create, :show], :controller => :reimbursement_acceptances
      resources :payments, :except => [:show, :index] do
        get :file, :on => :member
      end
      get :check_request, :on => :member, :defaults => { :format => 'pdf' }
    end
  end

  resources :reimbursements, :only => [:index], :controller => :reimbursements

  resource :user_profile do
    get :password, :on => :member
    put :update_password, :on => :member
  end

  get 'profile' => 'user_profiles#edit', :as => :profile
  get 'profile/password' => 'user_profiles#password', :as => :profile_password
  resources :pages, :controller => 'pages'
  get 'reports/travel_expenses' => "reports#travel_expenses", :as => :travel_expenses_report

  root :to => 'pages#userguide'

end

app/views/reimbursements_lists/index.html.haml
- model_class = Reimbursement
= content_for :page_header do
  %h1= t('.title', :default => model_class.model_name.human(count: 2))

%nav.navbar.navbar-default.nav-tsp
  .container-fluid
    - collection
    = search_form_for @q, :class => "navbar-form pull-right" do |f|
      - s_opts = {'non-selected-text' => t(:events_any), 'number-displayed' => 2, 'n-selected-text' => t(:events_n) }
      = f.collection_select :request_event_id_in, Event.all, :id, :name, {}, :multiple => true, :data => s_opts
      - s_opts = {'non-selected-text' => t(:states_any), 'number-displayed' => 2, 'n-selected-text' => t(:states_n) }
      = f.select :state_in, reimbursement_states_collection, {}, :multiple => true, :data => s_opts
      = f.submit t(:search), :class => "btn btn-default"
      = link_to t(:reset_search), reimbursements_path, :class => "btn btn-default"

%table.table.table-striped
  %thead
    %tr
      %th= sort_link(@q, :id)
      %th= model_class.human_attribute_name(:user)
      %th= model_class.human_attribute_name(:event)
      %th= model_class.human_attribute_name(:approved_sum)
      %th= model_class.human_attribute_name(:total_sum)
      %th= model_class.human_attribute_name(:authorized_sum)
      %th= sort_link(@q, :state, [:state, "state_updated_at desc"])
  %tbody
    - collection.each do |reimb|
      %tr{:id => "request-#{reimb.id}"}
        %td.id= link_to "#{reimb.label}", request_reimbursement_path(reimb.request)
        %td.user= reimb.user.try(:title)
        %td.event= reimb.event.try(:name)
        %td.approved= expenses_sum(reimb, :approved)
        %td.total= expenses_sum(reimb, :total)
        %td.authorized= expenses_sum(reimb, :authorized)
        %td.state= timestamped_state(reimb)
  %tfoot
    - if @all_reimbursements.size > @collection.size
      %tr
        %td
        %td
        %th.text-right= t(:page_total)
        %td= expenses_sum(@all_reimbursements, :approved)
        %td= expenses_sum(@all_reimbursements, :total)
        %td= expenses_sum(@all_reimbursements, :authorized)
        %td
    %tr
      %td
      %td
      %th.text-right= t(:full_total)
      %td= expenses_sum(@collection, :approved)
      %td= expenses_sum(@collection, :total)
      %td= expenses_sum(@collection, :authorized)
      %td

= paginate collection