config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  devise_for :users,
    :controllers => { :registrations => 'registrations',
                      :ichain_registrations => "ichain_registrations"},
    :failure_app => Devise::IchainFailureApp

  concern :state_machine do
    resources :state_transitions, :only => [:new, :create]
    resources :state_adjustments, :only => [:new, :create]
  end

  concern :commentable do
    resources :comments, :only => [:new, :create]
  end

  resources :events do
    resources :event_emails, except: [:edit, :update, :destroy] do
      post :preview, on: :collection
    end
    get :participants, on: :member
    resources :event_organizers, except: [:edit, :update, :show] do
      get :autocomplete_user, :on => :collection
    end
  end
  resources :budgets

  resources :travel_sponsorships,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'travel_sponsorship'} do
    resource :expenses_approval, :only => [:edit, :update]
  end

  resources :shipments,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'shipment'}

  resources :requests, :only => [:index, :show] do
    resource :reimbursement, :concerns => [:state_machine, :commentable], :defaults => {:machine => 'reimbursement'} do
      resources :attachments, :only => [:show], :controller => :reimbursement_attachments
      resource  :acceptance, :only => [:new, :create, :show], :controller => :reimbursement_acceptances
      resources :payments, :except => [:show, :index] do
        get :file, :on => :member
      end
      get :check_request, :on => :member, :defaults => { :format => 'pdf' }
    end
  end

  resources :reimbursements, :only => [:index], :controller => :reimbursements

  resource :user_profile do
    get :password, :on => :member
    put :update_password, :on => :member
  end

  get 'profile' => 'user_profiles#edit', :as => :profile
  get 'profile/password' => 'user_profiles#password', :as => :profile_password
  resources :pages, :controller => 'pages'
  get 'reports/travel_expenses' => "reports#travel_expenses", :as => :travel_expenses_report

  root :to => 'pages#userguide'

end

app/models/user_profile.rb
# frozen_string_literal: true

#
# This model is used to keep most of the information related to the user
# identity and role, in order to keep the User model as empty as possible.
# The User model only contains fields and associations that are strictly
# related to authentication.
#
class UserProfile < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # The associated user (one to one association)
  belongs_to :user
  # The role of the user in the application (mainly used for permissions)
  belongs_to_active_hash :role, class_name: 'UserRole', shortcuts: [:name]

  after_initialize :set_default_attrs, if: :new_record?

  delegate :name, to: :role, prefix: true, allow_nil: true

  validates :role_id, presence: true

  audited

  scope :with_role, lambda { |role|
    if role.is_a?(UserRole)
      where(role_id: role.id)
    else
      where(role_id: UserRole.find_by_name(role.to_s).id)
    end
  }

  def set_default_attrs
    self.role_name ||= 'none'
  end

  # List of fields that are required for processing reimbursements but are
  # not present. The list of fields is set as a configuration parameter for
  # the application.
  #
  # @return [Hash] hash with the name of the fields as keys and its
  #             human-readable names as values
  def missing_fields
    fields = Rails.configuration.site['relevant_profile_fields']
    fields = fields.select { |f| send(f.to_sym).blank? }
    Hash[fields.map { |f| [f, self.class.human_attribute_name(f)] }]
  end
end

app/controllers/user_profiles_controller.rb
# frozen_string_literal: true

class UserProfilesController < ApplicationController
  force_ssl unless: proc { Rails.env.test? || Rails.env.development? }
  before_action :set_user_and_profile

  def update
    attrs = params.require(:user).permit(:country_code, :full_name, :location,
                                         :passport, :alternate_id_document, :birthday, :phone_number,
                                         :second_phone_number, :website, :blog, :description,
                                         :postal_address, :zip_code)
    if @profile.update_attributes(attrs)
      flash[:notice] = I18n.t(:profile_updated)
      redirect_to profile_path
    else
      flash[:error] = I18n.t(:profile_update_failed)
      render 'edit'
    end
  end

  def update_password
    if @user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in @user
      flash[:notice] = I18n.t(:password_updated)
    end
    render 'password'
  end

  private

  def set_user_and_profile
    @user = current_user
    @profile = @user.find_profile
  end

  def users_controller?
    true
  end
end

app/views/user_profiles/_profile_menu.html.haml
%ul.nav.nav-tabs
  =nav_tab :profile, profile_path
  - if user_signed_in_by_ichain?
    = nav_tab :account, edit_user_ichain_registration_path
  - else
    = nav_tab :account, edit_user_registration_path
    = nav_tab :password, profile_password_path

app/views/user_profiles/edit.html.haml
= content_for :page_header do
  %h1= current_user.nickname
= render 'profile_menu'
%br
= simple_form_for @profile, :url => user_profile_path, :as => :user do |f|
  .row
    .col-md-6
      .col-md-4
        = f.input :full_name
        = f.input :birthday, :as => :dpicker, :input_html => {class: 'form-control'}
        = f.input :country_code, :as => :country, :input_html => {:autocomplete => "off"}
        = f.input :location
        = f.input :postal_address
        = f.input :zip_code
        = f.input :description, :as => :text, :input_html => {:rows => 2}
    .col-md-6
      .col-md-4
        = f.input :phone_number, :as => :string
        = f.input :second_phone_number, :as => :string
        = f.input :passport
        = f.input :alternate_id_document
        = f.input :website, :as => :url
        = f.input :blog, :as => :url
  .row
    .col-md-12
      .well
        = f.button :submit, :class => 'btn btn-primary'

app/views/user_profiles/password.html.haml
= content_for :page_header do
	%h1= current_user.nickname

= render 'profile_menu'
%br
= simple_form_for(@user, :as => 'user', :url => update_password_user_profile_path, :html => { :method => :put, :class => 'form-horizontal' }, wrapper: :horizontal_form) do |f|
	.col-md-4
		= f.hidden_field :reset_password_token
		= f.error_notification
		= f.input :password
		= f.input :password_confirmation
	.well.col-md-12
		= f.button :submit, t(:change_password), :class => 'btn btn-primary col-md-offset-1'