config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  devise_for :users,
    :controllers => { :registrations => 'registrations',
                      :ichain_registrations => "ichain_registrations"},
    :failure_app => Devise::IchainFailureApp

  concern :state_machine do
    resources :state_transitions, :only => [:new, :create]
    resources :state_adjustments, :only => [:new, :create]
  end

  concern :commentable do
    resources :comments, :only => [:new, :create]
  end

  resources :events do
    resources :event_emails, except: [:edit, :update, :destroy] do
      post :preview, on: :collection
    end
    get :participants, on: :member
    resources :event_organizers, except: [:edit, :update, :show] do
      get :autocomplete_user, :on => :collection
    end
  end
  resources :budgets

  resources :travel_sponsorships,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'travel_sponsorship'} do
    resource :expenses_approval, :only => [:edit, :update]
  end

  resources :shipments,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'shipment'}

  resources :requests, :only => [:index, :show] do
    resource :reimbursement, :concerns => [:state_machine, :commentable], :defaults => {:machine => 'reimbursement'} do
      resources :attachments, :only => [:show], :controller => :reimbursement_attachments
      resource  :acceptance, :only => [:new, :create, :show], :controller => :reimbursement_acceptances
      resources :payments, :except => [:show, :index] do
        get :file, :on => :member
      end
      get :check_request, :on => :member, :defaults => { :format => 'pdf' }
    end
  end

  resources :reimbursements, :only => [:index], :controller => :reimbursements

  resource :user_profile do
    get :password, :on => :member
    put :update_password, :on => :member
  end

  get 'profile' => 'user_profiles#edit', :as => :profile
  get 'profile/password' => 'user_profiles#password', :as => :profile_password
  resources :pages, :controller => 'pages'
  get 'reports/travel_expenses' => "reports#travel_expenses", :as => :travel_expenses_report

  root :to => 'pages#userguide'

end

app/models/payment.rb
# frozen_string_literal: true

#
# Effective payment of a reimbursement
#
class Payment < ApplicationRecord
  # The associated reimbursement
  belongs_to :reimbursement, inverse_of: :payments

  validates :amount, :reimbursement, :currency, :date, :method, presence: true

  mount_uploader :file, AttachmentUploader

  audited except: [:file]
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  authorize_resource :request
  authorize_resource :reimbursement, through: :request, singleton: true
  authorize_resource through: :request
  skip_authorize_resource only: :file
  prepend_before_action :set_request
  before_action :set_reimbursement
  before_action :set_payment, only: %i[edit update destroy file]

  before_action :load_methods, except: :file

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.reimbursement = @reimbursement

    respond_to do |format|
      if @payment.save
        format.html { redirect_to request_reimbursement_url(@request), notice: t(:payment_create) }
        format.json { render :show, status: :created, location: @reimbursement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to request_reimbursement_url(@request), notice: t(:payment_update) }
        format.json { render :show, status: :updated, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to request_reimbursement_url(@request), notice: t(:payment_destroyed) }
      format.json { head :no_content }
    end
  end

  def file
    authorize! :update, @payment
    send_file @payment.file.path
  end

  protected

  def load_methods
    @methods = Rails.configuration.site['payment_methods']
  end

  def set_breadcrumbs
    @breadcrumbs = [label: @request, url: @request]
    @breadcrumbs << { label: Reimbursement.model_name.human,
                      url: request_reimbursement_path(request: @request) }
    @breadcrumbs << { label: Payment.model_name.human(count: 2) }
  end

  private

  def set_request
    @request = Request.find(params[:request_id])

    redirect_back(fallback_location: requests_url) unless @request
  end

  def set_reimbursement
    @reimbursement = @request.reimbursement

    redirect_back(fallback_location: reimbursements_url) unless @reimbursement
  end

  def set_payment
    @payment = Payment.find(params[:id])

    redirect_back(fallback_location: request_reimbursement_url(@request)) unless @payment
  end

  def payment_params
    payment = %i[date amount currency cost_amount cost_currency method code subject notes file file_cache]
    params.require(:payment).permit(payment)
  end
end

app/views/payments/_form.html.haml
%strong.label.label-default= Reimbursement.human_attribute_name(:event)
%br
= render @reimbursement.event
%br
%strong.label.label-default= Reimbursement.human_attribute_name(:user)
%br
= render @reimbursement.user
%br
%strong.label.label-default= Payment.human_attribute_name(:reimbursement)
%br
= render @reimbursement

- form_path = @payment.new_record? ? request_reimbursement_payments_path : request_reimbursement_payment_path
= simple_form_for(@payment, :url => form_path, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  %strong.label.label-default= Payment.model_name.human
  %br
  .col-md-6
    = f.input :date, :as => :dpicker
    = f.input :amount do
      = f.text_field :amount
      = f.select :currency, currencies_for_select(:approved), {}
    = f.input :method, :collection => @methods
    = f.input :cost_amount do
      = f.text_field :cost_amount
      = f.select :cost_currency,currencies_for_select(:approved), {}
    = f.input :code
    = f.input :subject
    = f.input :notes, :input_html => {:rows => 5}
    = f.input :file, :as => :fileupload

  .well.col-md-12
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), request_reimbursement_path(@request), :class => 'btn btn-default'

app/views/payments/edit.html.haml
- model_class = @payment.class
= content_for :page_header do
  %h1= t('.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human)

= render :partial => "form"

app/views/payments/new.html.haml
- model_class = @payment.class
= content_for :page_header do
  %h1= t('.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human)

= render :partial => "form"