config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  devise_for :users,
    :controllers => { :registrations => 'registrations',
                      :ichain_registrations => "ichain_registrations"},
    :failure_app => Devise::IchainFailureApp

  concern :state_machine do
    resources :state_transitions, :only => [:new, :create]
    resources :state_adjustments, :only => [:new, :create]
  end

  concern :commentable do
    resources :comments, :only => [:new, :create]
  end

  resources :events do
    resources :event_emails, except: [:edit, :update, :destroy] do
      post :preview, on: :collection
    end
    get :participants, on: :member
    resources :event_organizers, except: [:edit, :update, :show] do
      get :autocomplete_user, :on => :collection
    end
  end
  resources :budgets

  resources :travel_sponsorships,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'travel_sponsorship'} do
    resource :expenses_approval, :only => [:edit, :update]
  end

  resources :shipments,
            :concerns => [:state_machine, :commentable],
            :defaults => {:machine => 'shipment'}

  resources :requests, :only => [:index, :show] do
    resource :reimbursement, :concerns => [:state_machine, :commentable], :defaults => {:machine => 'reimbursement'} do
      resources :attachments, :only => [:show], :controller => :reimbursement_attachments
      resource  :acceptance, :only => [:new, :create, :show], :controller => :reimbursement_acceptances
      resources :payments, :except => [:show, :index] do
        get :file, :on => :member
      end
      get :check_request, :on => :member, :defaults => { :format => 'pdf' }
    end
  end

  resources :reimbursements, :only => [:index], :controller => :reimbursements

  resource :user_profile do
    get :password, :on => :member
    put :update_password, :on => :member
  end

  get 'profile' => 'user_profiles#edit', :as => :profile
  get 'profile/password' => 'user_profiles#password', :as => :profile_password
  resources :pages, :controller => 'pages'
  get 'reports/travel_expenses' => "reports#travel_expenses", :as => :travel_expenses_report

  root :to => 'pages#userguide'

end

app/models/shipment.rb
# frozen_string_literal: true

#
# Request from a user to receive a merchandising box for a designated event
#
class Shipment < Request
  # Postal address extracted to another model
  belongs_to :postal_address, dependent: :destroy, autosave: true

  accepts_nested_attributes_for :postal_address, allow_destroy: false

  before_validation :ensure_postal_address

  # @see HasComments.allow_all_comments_to
  allow_all_comments_to :material
  # @see HasComments.allow_public_comments_to
  allow_public_comments_to %i[shipper requester]

  state_machine :state, initial: :incomplete do |_machine|
    event :submit do
      transition incomplete: :submitted
    end

    event :approve do
      transition submitted: :approved
    end

    event :dispatch do
      transition approved: :sent
    end

    event :confirm do
      transition sent: :received
    end

    event :roll_back do
      transition submitted: :incomplete
      transition approved: :incomplete
    end

    # The empty block for this state is needed to prevent yardoc's error
    # during automatic documentation generation
    state :canceled do
    end
  end

  # @see HasState.assign_state
  # @see HasState.notify_to
  assign_state :incomplete, to: :requester
  notify_state :incomplete, to: %i[requester material],
                            remind_to: :requester,
                            remind_after: 5.days

  assign_state :submitted, to: :material
  notify_state :submitted, to: %i[requester material],
                           remind_after: 10.days

  assign_state :approved, to: :shipper
  notify_state :approved, to: %i[requester material shipper],
                          remind_after: 5.days

  assign_state :sent, to: :requester
  notify_state :sent, to: %i[requester material shipper],
                      remind_after: 15.days

  notify_state :received, to: %i[requester material shipper]

  notify_state :canceled, to: %i[requester material shipper]

  # @see HasState.allow_transition
  allow_transition :submit, :requester
  allow_transition :approve, :material
  allow_transition :dispatch, :shipper
  allow_transition :confirm, :requester
  allow_transition :roll_back, %i[requester material]
  allow_transition :cancel, %i[requester material supervisor]

  delegate :shipment_type, to: :event

  # Check is the shipment can still be canceled
  #
  # @return [Boolean] true if it have not been sent yet
  def can_cancel?
    %i[incomplete submitted approved].include? state.to_sym
  end

  # Populate some fields with information read from the event and the user
  # profile, creating the associated PostalAddress object if it's missing
  #
  # @param [User] contact user to read the information from. By default, the one
  #             associated to the request.
  def populate_contact_info(contact = user)
    build_postal_address if postal_address.nil?
    postal_address.country_code ||= event.country_code unless event.nil?
    return unless contact

    profile = contact.profile
    # Phone number
    self.contact_phone_number ||= profile.phone_number
    self.contact_phone_number = profile.second_phone_number if contact_phone_number.blank?
    # Name
    postal_address.name ||= profile.full_name
    postal_address.name = contact.nickname if postal_address.name.blank?
  end

  protected

  def ensure_postal_address
    build_postal_address if postal_address.nil?
  end
end

app/controllers/shipments_controller.rb
# frozen_string_literal: true

class ShipmentsController < ApplicationController
  skip_load_resource only: %i[index new]
  before_action :set_states_collection, only: [:index]
  before_action :set_event, only: [:new]
  before_action :set_shipment, only: %i[show edit update destroy]

  def index
    @q ||= Shipment.accessible_by(current_ability).ransack(params[:q])
    @q.sorts = 'id asc' if @q.sorts.empty?
    @all_shipments ||= @q.result(distinct: true)
    @index ||= @all_shipments.page(params[:page]).per(20)
  end

  def show; end

  def new
    @shipment = Shipment.new
    @shipment.event = @event
    @shipment.user = current_user
    @shipment.populate_contact_info
    authorize! :create, @shipment
  end

  def create
    @shipment = Shipment.new(shipment_params)
    @shipment.user = current_user

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to shipment_url(@shipment), notice: t(:shipment_create) }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to shipment_url(@shipment), notice: t(:shipment_update) }
        format.json { render :show, status: :updated, location: @shipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shipment.destroy

    respond_to do |format|
      format.html { redirect_to shipments_url, notice: t(:shipment_destroyed) }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])

    redirect_back(fallback_location: events_url) unless @event
  end

  def set_shipment
    @shipment = Shipment.find(params[:id])

    redirect_back(fallback_location: shipments_url) unless @shipment
  end

  def set_states_collection
    @states_collection = Shipment.state_machines[:state].states.map { |s| [s.human_name, s.value] }
  end

  def shipment_params
    postal_address_attributes = %i[line1 line2 city county postal_code country_code]
    params.require(:shipment).permit(:event_id, :description, :contact_phone_number, postal_address_attributes: postal_address_attributes)
  end
end

app/views/shipments/_form.html.haml
%strong.label.label-default= Shipment.human_attribute_name(:event)
%br
= render @shipment.event
- unless @shipment.errors[:event_id].empty?
  %div.alert.alert-danger= @shipment.errors[:event_id].join("<br>")

%strong.label.label-default= Shipment.human_attribute_name(:shipment_type)
%br
%strong= @shipment.shipment_type
= simple_form_for(@shipment, html: { class: 'form-horizontal form-inputs' }, wrapper: :horizontal_form) do |f|
  %strong.label.label-default= t(:general_info)
  %br
  = f.hidden_field :event_id
  = f.input :description, :input_html => {:rows => 3}
  = f.input :contact_phone_number

  %strong.label.label-default= t("activerecord.attributes.shipment.postal_address")
  %br
  = f.simple_fields_for :postal_address do |a|
    .col-md-6
      = a.input :name
      = a.input :line1
      = a.input :line2, :as => :text
      = a.input :city
      = a.input :county
      = a.input :postal_code
      = a.input :country_code, :as => :country, :input_html => {:autocomplete => "off"}

  .well.col-md-12
    = f.button :submit, :class => 'btn btn-primary'
    - if @shipment.new_record?
      = link_to t('.cancel', :default => t("helpers.links.cancel")), @shipment.event, :class => 'btn btn-default'
    - else
      = link_to t('.cancel', :default => t("helpers.links.cancel")), @shipment, :class => 'btn btn-default'

app/views/shipments/edit.html.haml
- model_class = @shipment.class
= content_for :page_header do
  %h1= t('.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human)

= render :partial => "form"

app/views/shipments/index.html.haml
- model_class = Shipment
= content_for :page_header do
  %h1= t('.title', :default => model_class.model_name.human(count: 2))

%nav.navbar.navbar-default.nav-tsp
  .container-fluid
    = search_form_for @q, :class => "navbar-form pull-right" do |f|
      - s_opts = {'non-selected-text' => t(:events_any), 'number-displayed' => 2, 'n-selected-text' => t(:events_n) }
      = f.collection_select :event_id_in, Event.all, :id, :name, {}, :multiple => true, :data => s_opts
      - s_opts = {'non-selected-text' => t(:states_any), 'number-displayed' => 2, 'n-selected-text' => t(:states_n) }
      = f.select :state_in, @states_collection, {}, :multiple => true, :data => s_opts
      = f.submit t(:search), :class => "btn btn-default"
      = link_to t(:reset_search), shipments_path, :class => "btn btn-default"

%table.table.table-striped.shipments
  %thead
    %tr
      %th= sort_link(@q, :id)
      %th= model_class.human_attribute_name(:user)
      %th= model_class.human_attribute_name(:event)
      %th= model_class.human_attribute_name(:shipment_type)
      %th= sort_link(@q, :state, [:state, "state_updated_at desc"])
  %tbody
    - @index.each do |shipment|
      %tr{:id => "shipment-#{shipment.id}"}
        %td.id= link_to "#{shipment.label}", shipment
        %td.user= shipment.user.try(:title)
        %td.event= shipment.event.try(:name)
        %td.shipment_type= shipment.shipment_type
        %td.state= timestamped_state(shipment)

= paginate @index

app/views/shipments/new.html.haml
- model_class = @shipment.class
= content_for :page_header do
  %h1= t('.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human)

= render :partial => "form"

app/views/shipments/show.html.haml
- model_class = Shipment
= content_for :page_header do
  .row
    .col-md-7
      %h1= t('.title', :default => model_class.model_name.human) + " #{@shipment.label}"
    .col-md-5
      %br
      = state_change_links(@shipment)
      - if can? :edit, @shipment
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_shipment_path, :class => 'btn btn-default'
      - if can? :destroy, @shipment
        = link_to t('.destroy', :default => t("helpers.links.destroy")), @shipment, :method => "delete", :data => { :confirm => t("helpers.links.confirm") }, :class => 'btn btn-default'

= show_for @shipment do |r|
  .row
    .col-md-6
      = r.attribute :state do
        = state_info(r.object)
        %div.alert-info= @shipment.human_state_guide
      = r.attribute :shipment_type
    .col-md-6
      = r.association :event do
        = render @shipment.event
      = r.association :user do
        = render @shipment.user
  .row
    .col-md-12
      = r.attribute :description do
        = simple_format(@shipment.description)
  .row
    .col-md-6
      = r.association :postal_address do
        = render @shipment.postal_address
    .col-md-6
      = r.attribute :contact_phone_number

  = r.attribute :history do
    = render :partial => "history", locals: { resource: @shipment }
    - if can?(:create, @shipment.comments.build)
      = link_to(t(:create_comment), shipment_path + "/comments/new.js", :remote => true, :class => 'btn btn-default btn-sm')